name: KubeFlex Compatibility Matrix

on: 
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:
    inputs:
      kubestellar_ref:
        description: 'KubeStellar git ref (branch, tag, or commit)'
        required: true
        default: 'main'

permissions:
  contents: read

jobs:
  generate-matrix:
    name: Generate KubeFlex version matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - name: Generate kflex version matrix
        id: generate
        run: |
          MIN_VERSION="v0.8.0"
          MATRIX_VERSIONS=$(curl -s "https://api.github.com/repos/kubestellar/kubeflex/releases" | jq -r --arg MIN_VERSION "$MIN_VERSION" '[.[] | .tag_name | select(test("^v[0-9]+\\.[0-9]+\\.[0-9]+$")) | select(. >= $MIN_VERSION)]')
          echo "matrix=$MATRIX_VERSIONS" >> $GITHUB_OUTPUT

  test-kubeflex-version:
    name: Test with kflex ${{ matrix.kflex_version }}
    needs: [generate-matrix]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kflex_version: ${{ fromJson(needs.generate-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ github.event.inputs.kubestellar_ref || 'main' }}

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: '1.24'
          cache: true

      - name: Install kubectl
        uses: azure/setup-kubectl@776406bce94f63e41d621b960d78ee25c8b76ede

      - uses: ko-build/setup-ko@d006021bd0c28d1ce33a07e7943d48b079944c8d

      - name: Install dependencies
        run: |
          bash <(curl -L https://raw.githubusercontent.com/open-cluster-management-io/clusteradm/main/install.sh)
          go install github.com/onsi/ginkgo/v2/ginkgo

      - name: Download and install kflex
        run: |
          KFLEX_VERSION=${{ matrix.kflex_version }}
          wget https://github.com/kubestellar/kubeflex/releases/download/${KFLEX_VERSION}/kubeflex_${KFLEX_VERSION#v}_linux_amd64.tar.gz
          tar -xvf kubeflex_${KFLEX_VERSION#v}_linux_amd64.tar.gz bin/kflex
          sudo mv bin/kflex /usr/local/bin

      - name: Run e2e tests
        env:
          KFLEX_DISABLE_CHATTY: "true"
        run: |
          cd test/e2e/ginkgo
          ginkgo -vv --trace --no-color --fail-fast -- -kubestellar-setup-flags="--kubestellar-controller-manager-verbosity 5 --transport-controller-verbosity 5"
